---
- name: Create output directory for each device
  file:
    path: "{{save_dir}}"
    state: directory

- name: Pushing configuration, doing a commit check, getting the diff, and rollbacking 
  juniper_junos_config:
    provider: "{{ credentials }}"
    load: "{{ load_type }}"
    src: "{{ junos_conf_dir }}/{{ inventory_hostname }}.conf"
    diff: true
    diffs_file: "{{ save_dir }}/configuration_diff.log"
    check: true
    commit: false

- name: Pushing config, doing a commit check, downloading candidate config, and rollbacking   
  juniper_junos_config:
    load: "{{ load_type }}"
    provider: "{{ credentials }}"
    src: "{{ junos_conf_dir }}/{{ inventory_hostname }}.conf"
    retrieve: 'candidate'
    diff: false
    check: true
    commit: false
    dest: "{{save_dir}}/candidate-rendered-{{ inventory_hostname }}.conf"
